/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package faceRecognition;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.util.logging.Logger;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.lang.Math;

import faceRecognition.FacerecognitionGrpc;
import faceRecognition.FacerecognitionOuterClass.FaceRecognitionRequest;
import faceRecognition.FacerecognitionOuterClass.FaceRecognitionReply;
import faceRecognizer.faceRecognizer;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import edgeOffloading.OffloadingGrpc;
import edgeOffloading.OffloadingOuterClass.OffloadingRequest;
import edgeOffloading.OffloadingOuterClass.OffloadingReply;

public class FaceServer {
  private static final Logger logger = Logger.getLogger(FaceServer.class.getName());
	private static double effectiveRate = 0;
	private static double maxRate = 0;
	private static double minRate = 0;
	private static final double alpa = 0.5;

  private Server server;

  private void start() throws IOException {
    /* The port on which the server should run */
    int port = 50052;
    server = ServerBuilder.forPort(port)
        .addService(new FaceRecognitionImpl())
        .build()
        .start();
    logger.info("Face Recognition Server started, listening on " + port);
		faceRecognizer face = new faceRecognizer();
		face.load();
    Runtime.getRuntime().addShutdownHook(new Thread() {
      @Override
      public void run() {
        // Use stderr here since the logger may have been reset by its JVM shutdown hook.
        System.err.println("*** shutting down gRPC server since JVM is shutting down");
        FaceServer.this.stop();
        System.err.println("*** server shut down");
      }
    });
  }

  private void stop() {
    if (server != null) {
      server.shutdown();
    }
  }

  /**
   * Await termination on the main thread since the grpc library uses daemon threads.
   */
  private void blockUntilShutdown() throws InterruptedException {
    if (server != null) {
      server.awaitTermination();
    }
  }

  /**
   * Main launches the server from the command line.
   */
  public static void main(String[] args) throws IOException, InterruptedException {
    final FaceServer server = new FaceServer();
    server.start();
    server.blockUntilShutdown();
  }

	static class FaceRecognitionImpl extends FacerecognitionGrpc.FacerecognitionImplBase {

		@Override 
	  public void offloading(FaceRecognitionRequest req, StreamObserver<FaceRecognitionReply> responseObserver) {
			BufferedOutputStream mBufferedOutputStream = null;
			String filename = "";
			byte[] data = req.getData().toByteArray();
			double dataSize = data.length;
			String name = req.getName();
			try {
				filename = "receive_test.jpg";
				mBufferedOutputStream = new BufferedOutputStream(new FileOutputStream(filename));
				mBufferedOutputStream.write(data);
				mBufferedOutputStream.flush();
			} catch (Exception e) {
				e.printStackTrace();
			}
			try {
				mBufferedOutputStream.close();
			} catch (IOException e) {
				e.printStackTrace();
			} finally {
				mBufferedOutputStream = null;
			}
			faceRecognizer face = new faceRecognizer();
			long begin = System.currentTimeMillis();
			face.recognize("receive_1.jpg");
			long end = System.currentTimeMillis();
			System.out.println("Processing time: " + (end - begin) + " ms");
			FaceRecognitionReply reply = FaceRecognitionReply.newBuilder()
				.setMessage("You shall not pass!")
				.build();
			responseObserver.onNext(reply);
			responseObserver.onCompleted();
			// After finishing processing the request, update the speed information and decide whether to inform the change of speed to nbrs
			double currentRate = dataSize/(end-begin);
			/*
			if(effectiveRate == 0) {
				effectiveRate = currentRate;
			} else {
		  	effectiveRate = alpa * effectiveRate + (1 - alpa) * currentRate;
			}
			if((effectiveRate - minRate)/minRate > 0.1 || (effectiveRate - maxRate)/maxRate > 0.1) {
				updateInfo(effectiveRate);
			}
			minRate = Math.min(effectiveRate, minRate);
			maxRate = Math.max(effectiveRate, maxRate);
			*/
			String hostIP = System.getenv("HOSTIP");
			System.out.println(hostIP);
			updateInfo(currentRate);
		}

		private void updateInfo(double rate) {
			ManagedChannel mChannel;
			mChannel = ManagedChannelBuilder.forAddress("172.28.142.176", 50050).usePlaintext(true).build();
			OffloadingGrpc.OffloadingBlockingStub stub = OffloadingGrpc.newBlockingStub(mChannel);
			String hostIP = System.getenv("HOSTIP");
			OffloadingRequest message = OffloadingRequest.newBuilder().setMessage(hostIP + ":" + "face" + ":" + Double.toString(rate)).build();
			OffloadingReply reply = stub.startService(message);
		}
	}
}
